---
- name: is kubernetes already initialized
  stat: path=/etc/kubernetes/kubelet.conf
  register: kubernetes_path

- debug: msg="kubeadm init --api-advertise-addresses={{ master.ip }} --token {{ init_token }}"
  when: inventory_hostname in groups['master']

- name: initialize master
  command: "kubeadm init --api-advertise-addresses={{ master.ip }} --token {{ init_token }}"
  when:
    - inventory_hostname in groups['master']
    - kubernetes_path.stat.exists == false

- name: join nodes
  command: "kubeadm join --token {{ init_token }} {{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}"
  when: 
    - inventory_hostname in groups['worker'] 
    - kubernetes_path.stat.exists == false
