---
- name: Kubernetes - include subtask kubelet
  include: roles/kubelet.yml
  
- name: Kubernetes - include subtask apiserver
  include: roles/apiserver.yml

- name: Kubernetes - include subtask scheduler

- name: Kubernetes - include subtask manager

- name: Kubernetes - include enable services
  include: roles/enable.yml
