- name: add docker main repository
  template:
    src: docker-main.repo.j2
    dest: /etc/yum.repos.d/docker-main.repo

- name: create systemd override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: ansible_distribution_major_version == "7"

- name: add systemd override
  copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
  when: ansible_distribution_major_version == "7"
