- name: remove /etc/docker/key.json file
  file: path=/etc/docker/key.json state=absent

- name: stop and remove old containers
  docker:
    image: "{{ item }}"
    state: absent
  with_items:
    - swarm
    - gliderlabs/registrator
    - rethinkdb
    - shipyard/shipyard
  ignore_errors: True

- name: restart Docker service
  service: name=docker state=restarted enabled=yes
