---
- hosts: all
  remote_user: vagrant
  roles:
    - { role: common, become: yes, become_method: sudo }
    - { role: docker, become: yes, become_method: sudo }
    - { role: dockercompose, become: yes, become_method: sudo }
    - { role: kubernetes, become: yes, become_method: sudo }

- hosts: controller
  remote_user: vagrant
  roles:
    - { role: etcd, become: yes, become_method: sudo }
    - { role: kubernetes-controller, become: yes, become_method: sudo }
 
- hosts: worker
  remote_user: vagrant
  roles:
    - { role: kubernetes-worker, become: yes, become_method: sudo }
