---
- name: copy etcdctl to /usr/local/bin
  copy: src={{etcd_install_dir}}/{{etcd_installer_filename}}/etcdctl dest=/usr/local/bin/etcdctl remote_src=yes mode='a+x'
  when: "{{ etcd_installed }}"

- name: Update file permissions for binary
  file: path=/usr/local/bin/{{ files }} state=touch mode="a+x"
  with_items:
    - etcdctl
  loop_control:
    loop_var: files
