consul_installer_url_base: https://releases.hashicorp.com/consul
consul_installer_filename: "consul_{{ consul_version }}.zip"
consul_version: 0.6.3
consul_install_dir: /opt/consul
consul_log_level: INFO

consul_bind_interface: eth0
consul_dns_port: 8600
consul_http_port: 8500
consul_rpc_port: 8400

install_consul_ui: true
consul_web_ui_installer_filename: "consul_{{ consul_version }}_web_ui.zip"
consul_ui_install_dir: /opt/consul/ui
consul_data_dir: /opt/consul/data
consul_config_dir: /opt/consul/config
consul_config_file: /opt/consul/config/config.json
consul_log_dir: /opt/consul/logs

directories:
  - /opt/consul/scripts
  - /etc/consul.d/server
  - "{{ consul_install_dir }}"
  - "{{ consul_log_dir }}"
  - "{{ consul_data_dir }}"
  - "{{ consul_config_dir }}"
  - "{{ consul_ui_install_dir }}"

templates: [
  { src: "consul.conf.j2", dest: "/usr/lib/systemd/system/consul.service", mode: "0644" },
  { src: "bootstrap.json", dest: "/opt/consul/config/config.json", mode: "0644" }
] 

files: [
  { src: "mem_utilization.sh", dest: "/opt/consul/scripts/mem_utilization.sh", mode: "0755" },
  { src: "hdd_utilization.sh", dest: "/opt/consul/scripts/hdd_utilization.sh", mode: "0755" },
  { src: "cpu_utilization.sh", dest: "/opt/consul/scripts/cpu_utilization.sh", mode: "0755" }
]
