consul_installer_url_base: https://dl.bintray.com/mitchellh/consul
consul_installer_filename: "{{ consul_version }}_linux_amd64.zip"
consul_version: 0.5.2
consul_install_dir: /opt/consul
consul_log_level: INFO

consul_bind_interface: eth0
consul_dns_port: 8600
consul_http_port: 8500
consul_rpc_port: 8400

install_consul_ui: true
consul_web_ui_installer_filename: "{{ consul_version }}_web_ui.zip"
consul_ui_install_dir: /opt/consul/ui
consul_data_dir: /opt/consul/data
consul_config_dir: /opt/consul/config
consul_config_file: /etc/consul.d/server/config.json
consul_log_dir: /opt/consul/logs

directories:
  - /opt/consul/scripts
  - /etc/consul.d/server
  - "{{ consul_install_dir }}"
  - "{{ consul_log_dir }}"
  - "{{ consul_data_dir }}"
  - "{{ consul_config_dir }}"
  - "{{ consul_ui_install_dir }}"

templates: [
  { src: "consul.conf.j2", dest: "/usr/lib/systemd/system/consul.service", mode: "0644" },
  { src: "config.json", dest: "/etc/consul.d/server/config.json", mode: "0644" }
]
