---
- name: start swarm agents
  docker:
    name: swarm-agent
    image: swarm
    state: reloaded
    command: join --advertise="{{ ansible_eth1.ipv4.address}}":2375 consul://"{{common.master_ip}}"/
