---
- name: Swarm manager
  docker:
    image: swarm
    name: swarm-manager
    state: reloaded
    pull: always
    publish_all_ports: true
    restart_policy: unless-stopped
    ports:
      - "3375:2375"
    command: manage --strategy "{{swarm.strategy}}" consul://"{{common.master_ip}}"/
