---
- name: Swarm manager replica
  docker:
    image: swarm
    name: swarm-manager
    state: reloaded
    pull: always
    publish_all_ports: true
    restart_policy: unless-stopped
    ports:
      - "3375:2375"
    command: manage --strategy "{{swarm.strategy}}" --advertise="{{ ansible_eth1.ipv4.address}}":3375 --replication consul://"{{common.master_ip}}"/
