---
- name: Swarm pull
  docker:
    name: swarm_cluster
    image: swarm
    state: present

- name: Swarm create
  command: docker run --rm swarm create
  register: cluster_id
  when: ansible_fqdn == swarm.cluster 

- name: debug stuff
  debug: msg="{{cluster_id.stdout_lines}}"
