---
- name: Swarm manager
  docker:
    image: swarm
    name: swarm-manager
    state: restarted
    pull: always
    publish_all_ports: true
    ports:
      - "3375:2375"
    command: manage --strategy "{{swarm.strategy}}" consul://"{{common.master_ip}}"/
