---
- name: Swarm manager
  docker:
    image: swarm
    name: swarm-manager
    state: restarted
    pull: always
    publish_all_ports: true
    ports:
      - "3375:3375"
    command: manage -H tcp://0.0.0.0:3375 --strategy "{{swarm.strategy}}" consul://"{{common.master_ip}}"/swarm
