- name: restart systemd
  command: systemctl daemon-reload

- name: enable and start kube-apiserver
  service: name=kube-apiserver state=started enabled=yes

- name: enable and start kube-scheduler
  service: name=kube-scheduler state=started enabled=yes

- name: enable and start kube-master-manager
  service: name=kube-master-manager state=started enabled=yes
