---
- hosts: all
  remote_user: vagrant
  roles:
    - { role: common, become: yes, become_method: sudo }
    - { role: consul, become: yes, become_method: sudo }
    - { role: dnsmasq, become: yes, become_method: sudo }
    - { role: docker, become: yes, become_method: sudo }
    - { role: registrator, become: yes, become_method: sudo }
    - { role: dockerswarm, become: yes, become_method: sudo }
