---
- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
  - docker 
  - kubelet 
  - kubeadm 
  - kubectl 
  - kubernetes-cni
  - net-tools
  - nmap-ncat
  - wget
  - vim
  - python-devel
  - python-setuptools
  notify: 
    - enable docker

- name: Disable selinux
  command: setenforce 0
