---
- name: Add local bin to $PATH
  lineinfile: dest=/etc/environment regexp="^export PATH\=\/usr\/local\/bin" line="PATH=/usr/local/bin:$PATH"

- name: Create Directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items: directories

- name: Download etcd
  get_url: url={{ etcd_installer_url_base }}/{{etcd_installer_filename}}.tar.gz dest={{etcd_install_dir}}/{{etcd_installer_filename}}.tar.gz

- name: Unarchive etcd
  unarchive: copy=no src={{etcd_install_dir}}/{{ etcd_installer_filename }}.tar.gz dest={{ etcd_install_dir }}
  register: etcd_installed
