- name: restart cgconfig
  service:
    name: cgconfig
    state: restarted
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: start docker
  service:
    name: docker
    state: started
